driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: centos-6.7
  - name: centos-5.11
suites:
- name: default
  run_list:
  - recipe[auditd]

- name: rules
  run_list:
  - recipe[auditd::rules]

- name: stig-rules
  run_list:
  - recipe[auditd::rules]
  attributes:
    auditd:
      ruleset: "stig"
