driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.7
  - name: fedora-25
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
- name: default
  run_list:
  - recipe[auditd::rules]
  verifier:
    inspec_tests:
      - test/integration/default

- name: stig-rules
  run_list:
  - recipe[auditd::rules]
  attributes:
    auditd:
      ruleset: "stig"
  verifier:
    inspec_tests:
      - test/integration/stig

- name: capp-rules
  run_list:
  - recipe[auditd::rules]
  attributes:
    auditd:
      ruleset: "capp"
  verifier:
    inspec_tests:
      - test/integration/capp
