driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-15.04
    run_list:
    - recipe[apt]
  - name: centos-6.7
    run_list:
    - recipe[yum]
  - name: centos-7.1
    run_list:
    - recipe[yum]
  - name: centos-7.2
    run_list:
    - recipe[yum]

suites:
- name: default
  run_list:
  - recipe[auditd]

- name: rules
  run_list:
  - recipe[auditd::rules]

- name: stig-rules
  run_list:
  - recipe[auditd::rules]
  attributes:
    auditd:
      ruleset: "stig"

- name: capp-rules
  run_list:
  - recipe[auditd::rules]
  attributes:
    auditd:
      ruleset: "capp"
